/**
 * Generates the normative worked example for the Metered specification.
 *
 * A specification whose worked example was typed by hand is a specification with a bug in it. This
 * produces the whole session -- six chunks, a disagreement at chunk 4, settlement at the last
 * agreed state -- with real blake3 digests and real BIP340 signatures, so the document ships a
 * golden vector an implementer can check against rather than an illustration.
 *
 * Self-contained: uses the reference encoder, so it can be regenerated and compared.
 *   npm run vectors
 */
import { canonicalize, digestHex, blake3Hex, signEnvelope, verify, signState, verifyState, publicKeyHex } from '../src/encoding.js';

/**
 * Signatures are NOT part of the golden vector.
 *
 * BIP340 signs with random auxiliary data, so two correct signatures over the same message differ.
 * Discovered by regenerating this file and finding it did not reproduce. What implementations must
 * agree on byte-for-byte is the canonical encoding and its digest; a signature is verified, never
 * compared. So the vector pins the signing payload and reports only whether the signature checks.
 */
const pin = (label: string, obj: unknown, sig: { sig: string }, pubkey: string): string[] => [
  `  ${label}`,
  `    payload ${canonicalize(obj)}`,
  `    digest  ${digestHex(JSON.parse(canonicalize(obj)) as unknown)}`,
  `    sig     verifies=${verify(sig as object, pubkey)}  (bytes vary per signing; not pinned)`,
];

/* deterministic test keys -- never used for anything real */
const BUYER_SK = blake3Hex('metered/spec/vectors/buyer').slice(0, 64);
const PROVIDER_SK = blake3Hex('metered/spec/vectors/provider').slice(0, 64);
const BUYER_PK = publicKeyHex(BUYER_SK);
const PROVIDER_PK = publicKeyHex(PROVIDER_SK);

/* ------------------------------------------------------------------ the offer
 * Priced from the logged rate: $1 per 1M output tokens at $0.02755013/KAS is
 * 0.0000363 KAS per token, so 3630 sompi. A 550-token chunk is 1,996,500 sompi.
 */
const OFFER = {
  v: 1,
  scheme: 'metered',
  network: 'kaspa:testnet-10',
  asset: 'KAS',
  sessionId: blake3Hex('metered/spec/vectors/session').slice(0, 32), // SPEC.md 3.1: 16 bytes
  unit: 'llm.output_tokens.v1',
  tokenizer: 'o200k_base',
  unitPriceSompi: 3630,
  babelUnits: 550,
  maxBabels: 6,
  toleranceAbs: 1,
  
  checkpointEvery: 3,
  responseWindowDaa: 43200,
  buyerPubkey: BUYER_PK,
  providerPubkey: PROVIDER_PK,
  partiesCommitment: blake3Hex(BUYER_PK + PROVIDER_PK),
};

/** Per-chunk truth for the example. Chunk 4 is where the two sides disagree. */
const CHUNKS = [
  { seq: 0, delivered: 550, buyerSaw: 550 },
  { seq: 1, delivered: 550, buyerSaw: 550 },
  { seq: 2, delivered: 550, buyerSaw: 549 },   // the one-token divergence Study A measured
  { seq: 3, delivered: 550, buyerSaw: 550 },
  { seq: 4, delivered: 550, buyerSaw: 502 },   // outside tolerance -> halt
  { seq: 5, delivered: 550, buyerSaw: 550 },   // never happens; kept to show it is not reached
];

const sompiFor = (units: number) => units * OFFER.unitPriceSompi;
// SPEC.md 5 rule 4: absolute, and it does not scale with the babel. See src/reconcile.ts.
const toleranceFor = (providerUnits: number) => {
  void providerUnits;
  return OFFER.toleranceAbs;
};

const out: string[] = [];
const say = (s = '') => out.push(s);

say('METERED -- NORMATIVE WORKED EXAMPLE');
say('generated by spec/vectors.ts -- do not hand-edit');
say('='.repeat(78));
say();
say('KEYS (deterministic, test only)');
say(`  buyer    ${BUYER_PK}`);
say(`  provider ${PROVIDER_PK}`);
say();
say('OFFER (canonical form, signed by provider)');
say(canonicalize(OFFER));
say(`  digest ${digestHex(JSON.parse(canonicalize(OFFER)))}`);
say();

let prevStateDigest: string | null = null;
let agreedUnits = 0;
let agreedSompi = 0;
let halted = false;

for (const c of CHUNKS) {
  if (halted) {
    say(`CHUNK ${c.seq} -- not reached; the session halted at chunk ${c.seq - 1}`);
    say();
    continue;
  }

  say('-'.repeat(78));
  say(`CHUNK ${c.seq}`);

  const reservation = {
    v: 1,
    sessionId: OFFER.sessionId,
    seq: c.seq,
    units: OFFER.babelUnits,
    cumulativeUnits: agreedUnits + OFFER.babelUnits,
    cumulativeSompi: agreedSompi + sompiFor(OFFER.babelUnits),
    prevState: prevStateDigest,
  };
  const signedReservation = signEnvelope(reservation, BUYER_SK) as unknown as { sig: string };
  for (const line of pin('RESERVATION (buyer)', reservation, signedReservation, BUYER_PK)) say(line);

  // the bytes delivered in this chunk; the digest is over exactly these
  const wire = `chunk-${c.seq} of session ${OFFER.sessionId.slice(0, 12)}`;
  const contentDigest = blake3Hex(wire);

  const mkMeasurement = (by: 'buyer' | 'provider', units: number, cum: number) => ({
    v: 1,
    sessionId: OFFER.sessionId,
    seq: c.seq,
    by,
    units,
    cumulativeUnits: cum,
    contentDigest,
    measurementId: blake3Hex(`${OFFER.sessionId}/${c.seq}/${by}`).slice(0, 32),
  });

  const pmBody = mkMeasurement('provider', c.delivered, agreedUnits + c.delivered);
  const bmBody = mkMeasurement('buyer', c.buyerSaw, agreedUnits + c.buyerSaw);
  const pm = signEnvelope(pmBody, PROVIDER_SK) as unknown as { sig: string };
  const bm = signEnvelope(bmBody, BUYER_SK) as unknown as { sig: string };
  for (const line of pin('MEASUREMENT (provider)', pmBody, pm, PROVIDER_PK)) say(line);
  for (const line of pin('MEASUREMENT (buyer)', bmBody, bm, BUYER_PK)) say(line);

  const delta = Math.abs(c.delivered - c.buyerSaw);
  const allowed = toleranceFor(c.delivered);
  say(`  RECONCILE  delta=${delta}  allowed=${allowed}  -> ${delta <= allowed ? 'AGREE' : 'HALT'}`);

  if (delta > allowed) {
    halted = true;
    say(`  the session halts. Settlement uses State ${c.seq - 1}.`);
    say();
    continue;
  }

  // rule 6: bill the lower of the two counts
  const billed = Math.min(c.delivered, c.buyerSaw);
  agreedUnits += billed;
  agreedSompi += sompiFor(billed);

  const state = {
    v: 1,
    sessionId: OFFER.sessionId,
    seq: c.seq,
    cumulativeUnits: agreedUnits,
    cumulativeSompi: agreedSompi,
    prevState: prevStateDigest,
  };
  const stateDigest = digestHex(JSON.parse(canonicalize(state)));
  // a State carries TWO signatures, each computed with both absent -- see src/encoding.ts
  const buyerSig = signState(state, BUYER_SK);
  const providerSig = signState(state, PROVIDER_SK);
  const signedState = { ...state, buyerSig, providerSig };

  say(`  BILLED     ${billed} units (the lower of ${c.delivered} and ${c.buyerSaw})`);
  say('  STATE (both signatures required)');
  say('    payload ' + canonicalize(state));
  say(`    digest  ${stateDigest}`);
  say(`    buyer    verifies=${verifyState(signedState, buyerSig, BUYER_PK)}   provider verifies=${verifyState(signedState, providerSig, PROVIDER_PK)}`);

  prevStateDigest = stateDigest;

  if ((c.seq + 1) % OFFER.checkpointEvery === 0) {
    say(`  CHECKPOINT  anchor ${stateDigest}`);
    say('              non-blocking; the next chunk does not wait for it');
  }
  say();
}

say('='.repeat(78));
say('SETTLEMENT');
say(`  last agreed state   seq ${CHUNKS.findIndex((c) => Math.abs(c.delivered - c.buyerSaw) > toleranceFor(c.delivered)) - 1}`);
say(`  cumulativeUnits     ${agreedUnits}`);
say(`  cumulativeSompi     ${agreedSompi}   (${(agreedSompi / 1e8).toFixed(6)} KAS)`);
say(`  refunded to buyer   ${OFFER.maxBabels * sompiFor(OFFER.babelUnits) - agreedSompi} sompi`);
say();
say('  Cooperative close: both parties sign an ordinary spend for that split.');
say('  The covenant is not executed on this path.');

console.log(out.join('\n'));
