/**
 * Canonical encoding, digests and signatures for Metered.
 *
 * Vendored deliberately rather than imported. The golden vector was previously generated by
 * kaspa-depin's protocol package, which meant CI could not regenerate it and the specification's
 * most foundational claims were unverifiable from this repository. Two bugs had already survived
 * that gap; a third was found while writing this file.
 *
 * ONE HASH, EVERYWHERE. The borrowed code used BLAKE2b for message digests and BLAKE3 for content
 * addressing, and the specification said "digests are blake3" about both. An implementer following
 * the specification would have produced different `prevState` values and a different checkpoint
 * digest -- total incompatibility, from one sentence. Rather than document the accident, this
 * settles it: BLAKE3-256 for everything. The specification is now true.
 */
import { blake3 } from '@noble/hashes/blake3';
import { schnorr } from '@noble/curves/secp256k1';
import { bytesToHex, hexToBytes, utf8ToBytes } from '@noble/hashes/utils';

/**
 * RFC 8785 (JCS) canonical JSON.
 *
 * Keys sort by UTF-16 code unit, which is what JCS mandates and what JavaScript's default sort
 * does. This is NOT Unicode code-point order -- they diverge above the BMP, where surrogate pairs
 * sort below U+E000-FFFF. The specification said code point until a check caught it.
 */
export function canonicalize(value: unknown): string {
  if (value === null || typeof value === 'boolean') return JSON.stringify(value);
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error(`canonicalize: non-finite number ${value}`);
    return JSON.stringify(value);
  }
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalize).join(',')}]`;
  if (typeof value === 'object') return canonicalizeObject(value as Record<string, unknown>);
  throw new Error(`canonicalize: unsupported value of type ${typeof value}`);
}

function canonicalizeObject(value: Record<string, unknown>): string {
  const keys = Object.keys(value)
    .filter((k) => value[k] !== undefined)
    .sort(); // default sort is UTF-16 code unit order, which is what JCS requires
  return `{${keys.map((k) => `${JSON.stringify(k)}:${canonicalize(value[k])}`).join(',')}}`;
}

/** BLAKE3-256 of raw bytes or a UTF-8 string, hex. */
export function blake3Hex(input: Uint8Array | string): string {
  const bytes = typeof input === 'string' ? utf8ToBytes(input) : input;
  return bytesToHex(blake3(bytes, { dkLen: 32 }));
}

/** BLAKE3-256 of the canonical form of a value, hex. The only digest this protocol uses. */
export function digestHex(value: unknown): string {
  return blake3Hex(canonicalize(value));
}

export function publicKeyHex(privateKeyHex: string): string {
  return bytesToHex(schnorr.getPublicKey(hexToBytes(privateKeyHex)));
}

/**
 * Sign a message. The signature covers the canonical form with the signature field ABSENT --
 * not present-and-empty, which is a different byte string and a classic source of divergence.
 */
export function sign(message: object, privateKeyHex: string, field = 'sig'): string {
  const payload = withoutField(message, field);
  return bytesToHex(schnorr.sign(utf8ToBytes(canonicalize(payload)), hexToBytes(privateKeyHex)));
}

export function verify(message: object, publicKeyHexStr: string, field = 'sig'): boolean {
  const sig = (message as Record<string, unknown>)[field];
  if (typeof sig !== 'string') return false;
  try {
    const payload = withoutField(message, field);
    return schnorr.verify(hexToBytes(sig), utf8ToBytes(canonicalize(payload)), hexToBytes(publicKeyHexStr));
  } catch {
    return false;
  }
}

/** Attach a signature under `field`, leaving the original untouched. */
export function signEnvelope<T extends object>(message: T, privateKeyHex: string, field = 'sig'): T & Record<string, string> {
  return { ...message, [field]: sign(message, privateKeyHex, field) } as T & Record<string, string>;
}

/**
 * Kaspa script number, 8 bytes: little-endian magnitude with the sign in the top bit of the last
 * byte. This is what `OpNum2Bin(x, 8)` produces, and the covenant rebuilds the preimage with it,
 * so any disagreement here is a signature the chain cannot verify.
 */
function num2bin8(value: number): Uint8Array {
  if (!Number.isSafeInteger(value)) throw new Error(`num2bin8: ${value} is not a safe integer`);
  const out = new Uint8Array(8);
  let magnitude = Math.abs(value);
  for (let i = 0; i < 8; i += 1) {
    out[i] = magnitude % 256;
    magnitude = Math.floor(magnitude / 256);
  }
  // The index is in range by construction (out is a fixed 8-byte array), but the typechecker
  // cannot know that and noUncheckedIndexedAccess is worth keeping -- out-of-bounds is precisely
  // the family of bug this project keeps finding. Written so the compiler can see it too.
  if (value < 0) out[7] = (out[7] ?? 0) | 0x80;
  return out;
}

/**
 * SPEC.md 3.4.1 -- the settlement preimage. 72 bytes, fixed width, fixed order, no delimiters:
 * sessionId(16) + seq(8) + cumulativeUnits(8) + cumulativeSompi(8) + prevState(32).
 *
 * These 72 bytes are unique to a session only if the sessionId is. It is provider-chosen, so that
 * is not a property of this function -- SPEC.md 3.1a puts the obligation on the buyer to reject a
 * sessionId it has seen before, which src/offer.ts enforces.
 *
 * A State is the ONE signed object here whose signatures do not cover its canonical JSON. They
 * cannot: the covenant must reconstruct what it verifies and a Kaspa script cannot build canonical
 * JSON. Signing the JSON form yields a signature two peers accept and the chain cannot check --
 * a session that can never settle.
 *
 * `prevState` is 32 zero bytes at seq 0, where the JSON carries null. A null has no byte form.
 */
export function settlementPreimage(state: Record<string, unknown>): Uint8Array {
  const out = new Uint8Array(72);
  out.set(hexToBytes(state.sessionId as string), 0);
  out.set(num2bin8(state.seq as number), 16);
  out.set(num2bin8(state.cumulativeUnits as number), 24);
  out.set(num2bin8(state.cumulativeSompi as number), 32);
  const prev = state.prevState as string | null;
  if (prev) out.set(hexToBytes(prev), 40);
  return out;
}

/**
 * The 32 bytes both parties actually sign: blake3 of the preimage. The covenant computes exactly
 * this and hands it to `checkMsgSig`, which verifies a BIP340 signature over supplied data rather
 * than over the spending transaction.
 *
 * Neither signature field appears in the preimage at all, so the two parties sign identical bytes
 * and neither depends on the other having signed first. The old "canonical JSON with both fields
 * absent" rule is gone; there is nothing left to omit.
 */
export function settlementDigest(state: Record<string, unknown>): Uint8Array {
  return blake3(settlementPreimage(state), { dkLen: 32 });
}

/** Hex of the preimage. A string, so it can be compared, logged and pinned in a vector. */
export function stateSigningPayload(state: object): string {
  return bytesToHex(settlementPreimage(state as Record<string, unknown>));
}

export function signState(state: object, privateKeyHex: string): string {
  return bytesToHex(schnorr.sign(settlementDigest(state as Record<string, unknown>), hexToBytes(privateKeyHex)));
}

export function verifyState(state: object, sigHex: string, publicKeyHexStr: string): boolean {
  try {
    const digest = settlementDigest(state as Record<string, unknown>);
    return schnorr.verify(hexToBytes(sigHex), digest, hexToBytes(publicKeyHexStr));
  } catch {
    return false;
  }
}

function withoutField(obj: object, field: string): Record<string, unknown> {
  const copy: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) if (k !== field) copy[k] = v;
  return copy;
}
